### PR TITLE
Super feature

### LINKED ISSUE #8: Topics
Create function for Topics

### PR DESCRIPTION
**Pull request by BSchumann15**
hopefully no errors

### CODE REVIEW

**Review by minusInfinite — COMMENTED** [review]
It's not that there are errors, the Line Numbers in the main branch don't line up. Just need to check the line conflicts a align as needed

**Review by minusInfinite — APPROVED** [review]

**Comment by BSchumann15** [comment]
yeah the reason the lines dont add up is because i was adding routes from my modal to the existing index files

**Comment by minusInfinite** [comment]
Should be simple enough to resolve the conflict, once done it will be approved and merged.

**Comment by BSchumann15** [comment]
changed the conflicts

**Pull request merged**
